### ISSUE TITLE
edit footer layout

### ISSUE THREAD

**Issue by SURYOSIKHA** [SURYOSIKHA/Article-Architects_010#25]
- [x] change layout
- [x] add different colors
- [x] make it responsive 
- [x] add figma navbar and section-1 layout

**Comment by Annndyyyy** [comment]
Implement responsive design techniques to ensure that both sections of the footer adapt and display appropriately on various screen sizes and devices. This may involve using media queries, flexbox, or grid layout to adjust the layout and styling accordingly. Provide detailed step-by-step instructions for each aspect of responsiveness.
