### ISSUE TITLE
footer needs to be added

### ISSUE THREAD

**Issue by SURYOSIKHA** [SURYOSIKHA/Article-Architects_010#5]
- [x] add footer layout

**Comment by Annndyyyy** [comment]
* Divide the footer into two distinct sections to organize the content effectively.
*  Design the first section of the footer to include a heading, button, and paragraph providing relevant information.
*  Apply a purple background color to the entire first section of the footer for visual distinction.
*  Create the second section of the footer to encompass all remaining footer elements and apply a light gray background color for consistency.
*  Organize the content of the second section into five columns, with the first column containing the company logo.
*  Populate the second column with a list of applications offered by the company.
*  Populate the third column with a list of browser extensions provided by the company with respective icons.
* [ ]Populate the fourth column with a list of resources available to users, such as guides, tutorials, or downloads.
*  Populate the fifth column with information about the company, such as its mission, vision, and values.
*  Include copyright information and social media icons with links to the company's social profiles at the bottom of the footer.
*  Implement responsive design techniques to ensure that both sections of the footer adapt and display appropriately on various screen sizes and devices. This may involve using media queries, flexbox, or grid layout to adjust the layout and styling accordingly. Provide detailed step-by-step instructions for each aspect of responsiveness.
